In [1]:
#!/usr/bin/python3

import cv2
import numpy as np

#define function for finding diffrence between 3 images
def imgdiff(x,y,z):
    img1=cv2.absdiff(x,y)
    img2=cv2.absdiff(y,z)
    com_diff=cv2.bitwise_and(img1,img2)
    return com_diff

#initialize video capture device
cap=cv2.VideoCapture(0)

#read image from video capture device
frame1=cap.read()[1]
frame2=cap.read()[1]
frame3=cap.read()[1]

#change image color to grayscale
gray1=cv2.cvtColor(frame1,cv2.COLOR_BGR2GRAY)
gray2=cv2.cvtColor(frame2,cv2.COLOR_BGR2GRAY)
gray3=cv2.cvtColor(frame3,cv2.COLOR_BGR2GRAY)

while cap.isOpened():
    #call the function for finding diffrence between 3 images
    image_diff=imgdiff(gray1,gray2,gray3)
    #show image
    cv2.imshow('Diff_image',image_diff)
    frame=cap.read()[1]
    gray1=gray2
    gray2=gray3
    gray3=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    print(image_diff)
    if cv2.waitKey(1) & 0xff == ord('q'):
        break
cv2.destroyAllWindows()
cap.release()
    

[[3 4 0 ... 3 0 2]
 [1 0 0 ... 4 4 4]
 [0 0 4 ... 2 5 1]
 ...
 [0 0 0 ... 4 4 5]
 [0 1 1 ... 1 0 2]
 [6 2 0 ... 4 4 2]]
[[1 4 5 ... 2 0 0]
 [0 0 0 ... 0 0 2]
 [2 0 8 ... 0 1 1]
 ...
 [0 0 4 ... 0 0 0]
 [0 1 2 ... 1 0 1]
 [0 3 0 ... 0 0 0]]
[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 1 2 ... 0 0 5]
 ...
 [0 0 4 ... 0 0 2]
 [0 1 2 ... 1 0 1]
 [0 0 0 ... 0 0 0]]
[[4 0 2 ... 0 0 2]
 [0 0 1 ... 0 1 4]
 [0 4 0 ... 1 0 4]
 ...
 [0 0 0 ... 0 0 2]
 [0 1 2 ... 3 1 0]
 [0 0 2 ... 0 4 3]]
[[0 0 2 ... 1 2 4]
 [3 0 1 ... 0 3 6]
 [2 4 1 ... 1 2 2]
 ...
 [1 1 0 ... 1 0 3]
 [2 0 2 ... 3 0 0]
 [0 1 2 ... 0 0 0]]
[[ 0  5  4 ...  1 12 12]
 [ 1  0  4 ...  0  6  4]
 [ 2  2  1 ...  8  8  0]
 ...
 [ 0  0  0 ...  1  1  0]
 [ 1  2  0 ...  1  2  1]
 [ 0  0  0 ...  0  0  0]]
[[ 4  3  0 ...  2  0  0]
 [ 0  8  0 ...  0  4  0]
 [ 2  2  1 ...  8  0  0]
 ...
 [ 0  0  1 ...  1  1  0]
 [ 1  2  1 ...  8  0  0]
 [ 0  0  0 ...  9 12  0]]
[[12 10  0 ...  4  1  1]
 [ 2  0  1 ... 10 12  2]
 [ 2  0  9 ...  8  2  0]
 ...
 [ 1  0 

In [4]:

cap = cv2.VideoCapture(0)
while(1):
    # Take each frame
    frame = cap.read()[1]
    # Convert BGR to HSV
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    # define range of blue color in HSV
    lower_blue = np.array([110,50,50])
    upper_blue = np.array([130,255,255])
    # Threshold the HSV image to get only blue colors
    mask = cv2.inRange(hsv, lower_blue, upper_blue)
    # Bitwise-AND mask and original image
    res = cv2.bitwise_and(frame,frame, mask= mask)
    cv2.imshow('res',res)
    if cv2.waitKey(1) & 0xFF==ord('q') :
        break
cv2.destroyAllWindows()
cap.release()